Update flatpack-install
Add distro determine 
Add GTK theme adoption
Update Packages List

diff --git a/flatpack-install b/flatpack-install
--- a/flatpack-install
+++ b/flatpack-install
@@ -1,24 +1,69 @@
 #!/bin/bash
 
-# Install Flatpack 
-#sudo apt install flatpak
-flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
+## Install Flatpack 
 
-# Install Flatpacks
-flatpak install -y flathub com.spotify.Client
-flatpak install -y flathub org.videolan.VLC
-flatpak install -y flathub com.visualstudio.code
-flatpak install -y flathub com.dropbox.Client
-flatpak install -y flathub org.filezillaproject.Filezilla
-flatpak install -y flathub io.github.shiftey.Desktop
-flatpak install -y flathub org.gnome.Lollypop
-flatpak install -y flathub com.github.Bleuzen.FFaudioConverter
-flatpak install -y flathub com.makemkv.MakeMKV
-flatpak install -y flathub com.atlauncher.ATLauncher
-flatpak install -y flathub com.moonlight_stream.Moonlight
-flatpak install -y flathub com.brave.Browser
-flatpak install -y flathub org.deluge_torrent.deluge
-flatpak install -y flathub com.ultimaker.cura
+# Determine distribution
+if [ -f /etc/os-release ]; then
+    . /etc/os-release
+    DISTRO=$ID
+else
+    echo "Cannot determine the distribution."
+    exit 1
+fi
 
-# Reboot
-sudo reboot
+# Install Flatpak based on the distribution
+case $DISTRO in
+    ubuntu|debian)
+        sudo apt update
+        sudo apt install -y flatpak
+        sudo apt install -y gnome-software-plugin-flatpak
+        flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
+        ;;
+
+    fedora)
+        sudo dnf install -y flatpak
+        flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
+        ;;
+
+    centos|rhel)
+        sudo yum install -y flatpak
+        flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
+        ;;
+
+    opensuse)
+        sudo zypper install -y flatpak
+        flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
+        ;;
+
+    arch|manjaro)
+        sudo pacman -Sy flatpak
+        flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
+        ;;
+
+    *)
+        echo "Unsupported distribution."
+        exit 1
+        ;;
+esac
+
+## Apply GTK System Themes To Flatpak Apps
+sudo flatpak override --filesystem=$HOME/.local/share/themes
+sudo flatpak override --filesystem=$HOME/.local/share/icons
+sudo flatpak override --env=GTK_THEME=Dracula
+sudo flatpak override --env=ICON_THEME=Dracula 
+
+## Install Flatpacks
+flatpak install -y --noninteractive flathub com.spotify.Client
+flatpak install -y --noninteractive flathub org.videolan.VLC
+flatpak install -y --noninteractive flathub com.visualstudio.code
+flatpak install -y --noninteractive flathub com.dropbox.Client
+flatpak install -y --noninteractive flathub org.filezillaproject.Filezilla
+flatpak install -y --noninteractive flathub io.github.shiftey.Desktop
+flatpak install -y --noninteractive flathub org.gnome.Lollypop
+flatpak install -y --noninteractive flathub com.github.Bleuzen.FFaudioConverter
+flatpak install -y --noninteractive flathub com.makemkv.MakeMKV
+flatpak install -y --noninteractive flathub fr.handbrake.ghb
+flatpak install -y --noninteractive flathub io.gdevs.GDLauncher
+flatpak install -y --noninteractive flathub com.moonlight_stream.Moonlight
+flatpak install -y --noninteractive flathub com.ultimaker.cura
+
